#!/bin/bash

set -e -u

sudo cp .appveyor/data/ssl-cert-snakeoil.crt /etc/ssl/certs/ssl-cert-snakeoil.pem
sudo cp .appveyor/data/ssl-cert-snakeoil.key /etc/ssl/private/ssl-cert-snakeoil.key

sudo a2enmod ssl
sudo systemctl restart apache2

sudo a2ensite default-ssl
sudo systemctl reload apache2
