#!/bin/bash

set -e -u

if [ "X$1" == "X--warn-only" ]; then
    relaxed=True
    shift
else
    relaxed=""
fi

python_version="$1"; shift
git_version="$1"; shift
git_annex_version="$1"; shift

fails=0
function check() {
  if [ "X$2" != "X$3" ]; then
    if [ $relaxed ]; then
      echo -n WARNING
    else
      echo -n ERROR
      fails=$(( $fails + 1 ))
    fi
    echo : $1: version mismatch. Got $2, expected $3
  fi
}

check python $( { python --version || echo Python unknown; } |cut -d " " -f 2|cut -d "." -f 1-2) $python_version
check git $( { git --version || echo git version unknown; } |cut -d " " -f 3) $git_version
check git-annex $( { git annex version || echo git-annex version: unknown; } |head -1|cut -d " " -f 3) $git_annex_version

if [ $fails -gt 0 ]; then
  exit 1
fi
